name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: other-mods
    attributes:
      label: Mods
      description: Is Dead Money the only mod?
      options:
        - label: Dead Money is the only loaded mod.
  - type: input
    id: version
    attributes:
      label: Victoria 3 Version
      description: What version of Victoria 3 are you using?
      placeholder: 1.5.4
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Dead Money Version
      description: What version of Dead Money are you using?
      placeholder: 0.1.0
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Also tell us, what did you expect to happen?
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        If you don't know which log file to upload, just upload `C:\Users\<USERNAME>\Documents\Paradox Interactive\Victoria 3\logs\debug.log`

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
